baseURL = 'https://coinstr.app'
languageCode = 'en-us'
title = 'Coinstr'
paginate = 3
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "Coinstr is a multisignature Bitcoin wallet that allows users to configure and execute complex spending policies"
  author = 'Max Gravitt'

  # [params.comments]
  #   githubRepo = 'canhtran/maverick'
  #   theme = 'github-light'

[menu]
  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/"
  #   weight = "-300"
  # [[menu.main]]
  #   identifier = "resume"
  #   name = "Resume"
  #   url = "/resume/"
  #   weight = "-300"
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = -200
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = -150

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = true
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 6

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
